
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nimna
 */
public class GUI_Order extends javax.swing.JFrame {

    
    Connection con;
    PreparedStatement pst;
    
    //Creates new form GUI_Order
    public GUI_Order() {
        initComponents();
        con =SQLCON.connect(); //call the method  and store the connection in the con
        lbl_GT.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_s1 = new javax.swing.JSpinner();
        txt_s2 = new javax.swing.JSpinner();
        txt_s3 = new javax.swing.JSpinner();
        rb_1 = new javax.swing.JRadioButton();
        rb_2 = new javax.swing.JRadioButton();
        rb_3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_s4 = new javax.swing.JSpinner();
        txt_s5 = new javax.swing.JSpinner();
        txt_s6 = new javax.swing.JSpinner();
        rb_4 = new javax.swing.JRadioButton();
        rb_5 = new javax.swing.JRadioButton();
        rb_6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txt_s7 = new javax.swing.JSpinner();
        txt_s8 = new javax.swing.JSpinner();
        txt_s9 = new javax.swing.JSpinner();
        rb_7 = new javax.swing.JRadioButton();
        rb_8 = new javax.swing.JRadioButton();
        rb_9 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_delete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_GT = new javax.swing.JLabel();
        btn_place_order = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        jTabbedPane1.setBackground(new java.awt.Color(132, 94, 194));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(132, 94, 194)));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        txt_s1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        txt_s2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        txt_s3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        rb_1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_1.setForeground(new java.awt.Color(255, 255, 255));
        rb_1.setText("Burger");
        rb_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_1ActionPerformed(evt);
            }
        });

        rb_2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_2.setForeground(new java.awt.Color(255, 255, 255));
        rb_2.setText("Sandwich");
        rb_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_2ActionPerformed(evt);
            }
        });

        rb_3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_3.setForeground(new java.awt.Color(255, 255, 255));
        rb_3.setText("Pizza");
        rb_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizza.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sandwich.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hamburger.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_s1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_s2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_2))
                .addGap(96, 96, 96)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_s3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rb_2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(rb_3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rb_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        txt_s1.getAccessibleContext().setAccessibleDescription("");
        txt_s2.getAccessibleContext().setAccessibleDescription("");
        txt_s3.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Meals", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        txt_s4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        txt_s5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        txt_s6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s6.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        rb_4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_4.setForeground(new java.awt.Color(255, 255, 255));
        rb_4.setText("Ice Cream");

        rb_5.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_5.setForeground(new java.awt.Color(255, 255, 255));
        rb_5.setText("Pudding");
        rb_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_5ActionPerformed(evt);
            }
        });

        rb_6.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_6.setForeground(new java.awt.Color(255, 255, 255));
        rb_6.setText("Cheesecake");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ice-cream.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pudding.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cheesecake.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_s4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_s5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_5))
                .addGap(108, 108, 108)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_6)
                    .addComponent(txt_s6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_s4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(72, 72, 72))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_s5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rb_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_s6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Desserts", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 102, 255));

        txt_s7.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s7.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        txt_s7.setBorder(null);

        txt_s8.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        txt_s9.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        txt_s9.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        rb_7.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_7.setForeground(new java.awt.Color(255, 255, 255));
        rb_7.setText("Milkshake");
        rb_7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        rb_8.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_8.setForeground(new java.awt.Color(255, 255, 255));
        rb_8.setText("Smoothie");

        rb_9.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        rb_9.setForeground(new java.awt.Color(255, 255, 255));
        rb_9.setText("Cappuccino");
        rb_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_9ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/milkshake.png"))); // NOI18N
        jLabel10.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smoothie.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cappuccino.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_s7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(rb_7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_s8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_s9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rb_8)
                                    .addComponent(rb_7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_s8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_s7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rb_9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_s9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(7, 7, 7)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Beverages", jPanel3);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("Online Food Ordering System");

        btn_add.setBackground(new java.awt.Color(153, 102, 255));
        btn_add.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add Items");
        btn_add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_add.setBorderPainted(false);
        btn_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_add.setMaximumSize(new java.awt.Dimension(127, 23));
        btn_add.setMinimumSize(new java.awt.Dimension(123, 23));
        btn_add.setPreferredSize(new java.awt.Dimension(127, 23));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 102, 255));
        jLabel6.setText("Selected Items");

        jTable1.setBackground(new java.awt.Color(153, 102, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity", "Total"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(132, 94, 194));
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        btn_delete.setBackground(new java.awt.Color(153, 102, 255));
        btn_delete.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btn_delete.setForeground(java.awt.Color.white);
        btn_delete.setText("Clear");
        btn_delete.setBorderPainted(false);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 255));
        jLabel2.setText("Grand Total (Rs.):");

        lbl_GT.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lbl_GT.setForeground(new java.awt.Color(153, 102, 255));
        lbl_GT.setText("GT");

        btn_place_order.setBackground(new java.awt.Color(153, 102, 255));
        btn_place_order.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btn_place_order.setForeground(java.awt.Color.white);
        btn_place_order.setText("Place Order");
        btn_place_order.setBorderPainted(false);
        btn_place_order.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_place_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_place_orderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel6))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btn_delete)
                                .addGap(105, 105, 105)
                                .addComponent(btn_place_order))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_GT, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel6)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_GT))
                        .addGap(102, 102, 102))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_place_order)
                    .addComponent(btn_delete))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel model;
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
        int sum = 0;
        if(rb_1.isSelected() == true)
        {
            String burger = "Burger";
            int  price = 750;
            int  qty = Integer.parseInt(txt_s1.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                burger,
                price,
                qty,
                tot 
            }        
             );    
        }
         if(rb_2.isSelected() == true)
        {
           String sandwich  = "Sandwich";
            int  price = 350;
            int  qty = Integer.parseInt(txt_s2.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                sandwich,
                price,
                qty,
                tot 
            }        
             );    
        }
         
          if(rb_3.isSelected() == true)
        {
           String pizza  = "Pizza";
            int  price = 1600;
            int  qty = Integer.parseInt(txt_s3.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                pizza,
                price,
                qty,
                tot 
            }        
             );    
        }
          
          if(rb_4.isSelected() == true)
        {
            String ice_cream = "Ice Cream";
            int  price = 200;
            int  qty = Integer.parseInt(txt_s4.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                ice_cream,
                price,
                qty,
                tot 
            }        
             );    
        }
         if(rb_5.isSelected() == true)
        {
           String pudding  = "Pudding";
            int  price = 350;
            int  qty = Integer.parseInt(txt_s5.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                pudding,
                price,
                qty,
                tot 
            }        
             );    
        }
         
          if(rb_6.isSelected() == true)
        {
           String cheesecake  = "Cheesecake";
            int  price = 500;
            int  qty = Integer.parseInt(txt_s6.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                cheesecake,
                price,
                qty,
                tot 
            }        
             );    
        }
          
          if(rb_7.isSelected() == true)
        {
            String milkshake = "Milkshake";
            int  price = 450;
            int  qty = Integer.parseInt(txt_s7.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                milkshake,
                price,
                qty,
                tot 
            }        
             );    
        }
         if(rb_8.isSelected() == true)
        {
           String smoothie  = "Smoothie";
            int  price = 400;
            int  qty = Integer.parseInt(txt_s8.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                smoothie,
                price,
                qty,
                tot 
            }        
             );    
        }
         
          if(rb_9.isSelected() == true)
        {
           String cappuccino  = "Cappuccino";
            int  price = 250;
            int  qty = Integer.parseInt(txt_s9.getValue().toString());
            int tot = price * qty;   
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]          
            {
                cappuccino,
                price,
                qty,
                tot 
            }        
             );    
        }

        for(int i=0; i<jTable1.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());  
        }
        
        lbl_GT.setText(Integer.toString(sum));
        
        
        if((rb_1.isSelected() == false) && (rb_2.isSelected() == false)&&
             (rb_3.isSelected() == false) && (rb_4.isSelected() == false)&&
             (rb_5.isSelected() == false) && (rb_6.isSelected() == false)&&
             (rb_7.isSelected() == false) && (rb_8.isSelected() == false)&&
             (rb_9.isSelected() == false)){
            JOptionPane.showMessageDialog(null, "Select Items to Add");
        }
        
        //Reset Radiobuttons
        rb_1.setSelected(false);
        rb_2.setSelected(false);
        rb_3.setSelected(false);
        rb_4.setSelected(false);
        rb_5.setSelected(false);
        rb_6.setSelected(false);
        rb_7.setSelected(false);
        rb_8.setSelected(false);
        rb_9.setSelected(false);
        
        //Reset Jspinners to minimum value
        txt_s1.setValue(((SpinnerNumberModel) txt_s1.getModel()).getMinimum());
        txt_s2.setValue(((SpinnerNumberModel) txt_s2.getModel()).getMinimum());
        txt_s3.setValue(((SpinnerNumberModel) txt_s3.getModel()).getMinimum());
        txt_s4.setValue(((SpinnerNumberModel) txt_s4.getModel()).getMinimum());
        txt_s5.setValue(((SpinnerNumberModel) txt_s5.getModel()).getMinimum());
        txt_s6.setValue(((SpinnerNumberModel) txt_s6.getModel()).getMinimum());
        txt_s7.setValue(((SpinnerNumberModel) txt_s7.getModel()).getMinimum());
        txt_s8.setValue(((SpinnerNumberModel) txt_s8.getModel()).getMinimum());
        txt_s9.setValue(((SpinnerNumberModel) txt_s9.getModel()).getMinimum());
    }//GEN-LAST:event_btn_addActionPerformed

    private JFrame frame;
    private void btn_place_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_place_orderActionPerformed
        // TODO add your handling code here:
        
        
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        if(dtm.getRowCount()==0){
            //show message if table is empty
            JOptionPane.showMessageDialog(this, "Table is Empty");
        }else{
            //if table is not empty
            String Item,Price,Quantity,Total;
          try {
              
            int sum = 0;
            for(int i=0; i<jTable1.getRowCount(); i++)
            {
             sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());  
            }
        
             frame = new JFrame("Exit");
             if(JOptionPane.showConfirmDialog(frame,"The Grand Total is Rs."+sum+"\n" + 
                "Do you want to confirm your order?", "Place Order", 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
             {
            //Remove all table rows when order is placed
            /*DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0); 
            lbl_GT.setText("");*/
            }
             else{
                 return;
             }
            
            
            for (int i=0;i<dtm.getRowCount();i++){
                Item = dtm.getValueAt(i, 0).toString();
                Price = dtm.getValueAt(i, 1).toString();
                Quantity = dtm.getValueAt(i, 2).toString();
                Total = dtm.getValueAt(i, 3).toString();
                
                String sql = "INSERT INTO orders(Item,Price,Quantity,Total)VALUES (?,?,?,?)";        
                pst = con.prepareStatement(sql);
                
                pst.setString(1, Item);
                pst.setString(2, Price);
                pst.setString(3, Quantity);
                pst.setString(4, Total);
                
                pst.execute();
            }
            JOptionPane.showMessageDialog(this, "Order is inserted");
            //clear table
            dtm.setRowCount(0);
            //clear Grand Total
            lbl_GT.setText("");
          } catch (Exception e) {
        }
            
        }
       
    }//GEN-LAST:event_btn_place_orderActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        
        
        //delete row
        if(jTable1.getSelectedRowCount()==1){
            //select and delete a single row
            tblModel.removeRow(jTable1.getSelectedRow());
            
            //Update the total when row is deleted
        int sum = 0;
            for(int i=0; i<jTable1.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());  
        }
        
        lbl_GT.setText(Integer.toString(sum));
            
        }
        else {
            if(jTable1.getRowCount()==0){
                //display message if table is empty
                JOptionPane.showMessageDialog(this, "Table is empty");               
            }
            else{
                //display message if table is empty, but row is not selected, or multiple rows are selected
                JOptionPane.showMessageDialog(this, "Select a single row to delete");
            }
        }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void rb_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_1ActionPerformed

    private void rb_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_3ActionPerformed

    private void rb_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_2ActionPerformed

    private void rb_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_5ActionPerformed

    private void rb_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Order().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_place_order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_GT;
    private javax.swing.JRadioButton rb_1;
    private javax.swing.JRadioButton rb_2;
    private javax.swing.JRadioButton rb_3;
    private javax.swing.JRadioButton rb_4;
    private javax.swing.JRadioButton rb_5;
    private javax.swing.JRadioButton rb_6;
    private javax.swing.JRadioButton rb_7;
    private javax.swing.JRadioButton rb_8;
    private javax.swing.JRadioButton rb_9;
    private javax.swing.JSpinner txt_s1;
    private javax.swing.JSpinner txt_s2;
    private javax.swing.JSpinner txt_s3;
    private javax.swing.JSpinner txt_s4;
    private javax.swing.JSpinner txt_s5;
    private javax.swing.JSpinner txt_s6;
    private javax.swing.JSpinner txt_s7;
    private javax.swing.JSpinner txt_s8;
    private javax.swing.JSpinner txt_s9;
    // End of variables declaration//GEN-END:variables
}
